name: Go

env:
  FILE_NAME: 'hello-server'

on:
  push:
    branches: [ "main" ]

jobs:
  Build-Artefato-Go-Linux:
    runs-on: ubuntu-latest
    steps:      
      - name: Realizando Build do Artefato Go para Linux
        uses: actions/checkout@v4
        run: 'go build {{ env.FILE_NAME }}.go'
        
      - name: Upload artifact for linux
        uses: actions/upload-artifact@v1.0.0
        with:
          name: linux
          path: ./${{ env.FILE_NAME }}

  Build-Artefato-Go-Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Realizando Build do Artefato Go para Windows
        run: 'GOOS=windows GOARCH=amd64 go build {{ env.FILE_NAME }}.go'

      - name: Upload artifact for windows
        uses: actions/upload-artifact@v1.0.0
        with:
          name: windows
          path: ./${{ env.FILE_NAME }}.exe
