name: Go

env:
  FILE_NAME: 'hello-server'

on:
  push:
    branches: [ "main" ]

jobs:
  BuildGo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Build Linux
        run: go build -o ${{ env.FILE_NAME }}.go
        
      - name: Build Windows
        run: GOOS=windows GOARCH=amd64 go build ${{ env.FILE_NAME }}.go

      - name: Upload artifact for Linux
        uses: actions/upload-artifact@v1
        with:
          name: linux-artifact
          path: ./${{ env.FILE_NAME }}

      - name: Upload artifact for Windows
        uses: actions/upload-artifact@v1
        with:
          name: windows-artifact
          path: ./${{ env.FILE_NAME }}.exe
