name: Go

env:
  FILE_NAME: 'hello-server'

on:
  push:
    branches: [ "main" ]

jobs:
  BuildGo:
    runs-on: ubuntu-latest
    steps:
      - name: Build Linux
        uses: actions/checkout@v4
        with:
          path: go build {{ env.FILE_NAME }}.go
        
      - name: Build Windows
        uses: actions/checkout@v4
        with:
          path: GOOS=windows GOARCH=amd64 go build {{ env.FILE_NAME }}.go

      - name: Upload artifact for linux
        uses: actions/upload-artifact@v1.0.0
        with:
          name: linux
          path: ./${{ env.FILE_NAME }}

      - name: Upload artifact for windows
        uses: actions/upload-artifact@v1.0.0
        with:
          name: windows
          path: ./${{ env.FILE_NAME }}.exe
