name: Go

on:
  push:
    branches: 
      - main
  schedule:
    - cron: '*/15 * * * 1-6'      

jobs:
  BuildGo:
    runs-on: ubuntu-latest
    env:
      FILE_NAME: 'hello-server'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Build Linux
        run: go build ${{ env.FILE_NAME }}.go
        
      - name: Build Windows
        run: GOOS=windows GOARCH=amd64 go build ${{ env.FILE_NAME }}.go

      - name: Upload artifact for Linux
        uses: actions/upload-artifact@v3
        with:
          name: linux
          path: ./${{ env.FILE_NAME }}
          
      - name: Upload artifact for Windows
        uses: actions/upload-artifact@v3
        with:
          name: windows
          path: ./${{ env.FILE_NAME }}.exe

  download-and-run-linux:
    runs-on: ubuntu-latest
    needs: BuildGo
    steps:
      - name: Checar repositório
        uses: actions/checkout@v3

      - name: Download artefato Linux
        uses: actions/download-artifact@v3
        with:
          name: linux

      - name: Listar Arquivos do diretório (Comando para Linux)
        run: ls -la

      - name: Mudar permissõa run.sh para execução
        run: chmod +x ./run.sh

      - name: Rodar Script
        run: ./run.sh


  download-only-windows:
    runs-on: windows-latest
    needs: BuildGo
    steps:
      - name: Checar repositório
        uses: actions/checkout@v3

      - name: Download do artefato Windows
        uses: actions/download-artifact@v3
        with:
          name: windows

      - name: Listar Arquivos do diretório (Comando para Windows CMD)
        run: dir        
